### PR TITLE
Fix `TypeError` when setting `Embed.thumbnail` and `Embed.image` property

### PR DESCRIPTION
**Pull request by null2264**
## Summary

Fixed `TypeError: image() takes 1 positional argument but 2 were given`

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by isaa-ctaylor** [comment]
You are just supposed to do `url=`

**Comment by null2264** [comment]
But i did? My code is literally `e.set_image(url=avatar.with_size(1024).url)`

**Comment by isaa-ctaylor** [comment]
Could you show the code? From where you define `e`?

**Comment by null2264** [comment]
I think that's unrelated but here is the full code
```
e = discord.Embed(
        title="{}'s Avatar".format(user.name),
        description=links,
)
e.set_image(url=user.display_avatar.with_size(1024).url)
await ctx.reply(embed=e)
```

**Comment by isaa-ctaylor** [comment]
Could I see the full traceback as well? In the original error you mentioned (`TypeError: image() takes 1 positional argument but 2 were given`), `image()` seems to be the culprit, not set_image?

**Comment by null2264** [comment]
Yea it is `image()` that's what i changed in this PR,

`set_image` is just `self.image = new_url` that runs `image()` which is a setter for `image` property, and that setter's `url` param being keyword only breaks it...

**Comment by isaa-ctaylor** [comment]
Oh. I failed to look properly at what the code was, my bad, sorry!

**Review by iDutchy — CHANGES_REQUESTED** [review]
It has been brought to my attention that both image.setter and thumbnail.setter actually do not work if you later want to remove them. Changing to 

```
    @image.setter
    def image(self: E, *, url: Any):
        if url is EmptyEmbed:
            del self._image
        else:
            self._image = {
                'url': str(url),
            }
``` 
       and same for thumbnail should fix that

**Review by iDutchy — APPROVED** [review]

**Comment by iDutchy** [comment]
Looks good. There's only a stray `return` in the thumbnail.setter which can be removed. Also may need a `.. versionchanged:: 2.0` to add that image/thumbnail can now be set this way?

**Comment by null2264** [comment]
> Also may need a .. versionchanged:: 2.0 to add that image/thumbnail can now be set this way?

Like this?

```
.. versionchanged:: 2.0
    Can now be set without using `set_image()`
```
I'm not good at wording and stuff so...

**Comment by IAmTomahawkx** [comment]
Thanks

**Pull request merged**
