### PR TITLE
Update message.py

### PR DESCRIPTION
**Pull request by Hunter2807**
Now, when doing
```py
for word in message:
    print(word)
```
it will print all the words of the message, which are separated by a space!

## Summary

It is a PR so that the discord.Message can now be used in a for loop!

## Checklist

- [x ] If code changes were made then they have been tested.
    - [ x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Gnome-py** [comment]
This seems massively unnecessary. If anything this should be `yield from self.content` although that is a stretch. Disapprove

**Comment by Hunter2807** [comment]
May I know why do u think it is unnecessary?

**Comment by Hunter2807** [comment]
Also, `yield from self.content` would return every letter separately, not every word

**Comment by Gnome-py** [comment]
Weird behaviour for a default, in my opinion, this should be chosen in user code via `for word in str(message).split()` or `for word in message.content.split()`

**Comment by Hunter2807** [comment]
Yes, but I don't really think a user would need *every* letter of the content separately, but instead he would be needing every word. I don't really think there is a use to return every single letter of the word. Can I know any one good use case, where a person will be needing every single letter?

**Comment by Gnome-py** [comment]
Neither should be added, this should be left as is, being an opt in (via `str(message)` or `message.content`).

**Comment by Hunter2807** [comment]
Well, I don't really think there is any harm in adding this as a feature. If that is your argument, then why `str(message)` is there? `message.content` also speaks for itself, as to what it does.

**Comment by AlexFlipnote** [comment]
Just do `message.content.split()`, don't need the library to do a simple string argument for you.

**Comment by iDutchy** [comment]
str(message) exists because this is an extra feature, changing how you iterate over a string is a python builtin which should speak for itself more.

**Pull request closed without merging**
