### PR TITLE
Advise version incompatibility with Python 3.9.7

### PR DESCRIPTION
**Pull request by kuanhulio**
## Summary

Due to a bug in Python 3.9.7, code situations where we call an __init__ function in a subclass will fail with a TypeError. 

This is only a bug within the Python language and was patched out with Python 3.10 and this doesn't affect Python 3.9.6. 

Here, we are advising the incompatibility.

You can view that bug report [here on the Python Bugs site.](https://bugs.python.org/issue45121)

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [] This PR fixes an issue.
- [] This PR adds something new (e.g. new method or parameters).
- [] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by JDJGInc** [comment]
can you try updating your python 3.9.7 version to see if it fixes the issue or did they fix it in 3.9.8?

**Comment by kuanhulio** [comment]
Per my tests, 3.9.6 and 3.10.0 seem unaffected. I reinstalled Python 3.9.7 and the same edge case error happened.

**Comment by Gnome-py** [comment]
I feel like this should be left as a note in the affected places, instead of as a big notice at the top of the readme, on that note, where are the affected places? I have been running 3.9.7 for development since it came out on `pacman` and seem to have no problems.

**Comment by kuanhulio** [comment]
Well, on my hands, I'm working on Windows 10 with the 3.9.7 directly from python.org and it seemingly throws this error.

Affected areas would primarily be wherever a class derives from a `Protocol` and we call `super().__init__()`. I'm not really familiar with d.py codebase or the additions you guys have made, however, this specific error was called from `discord/ext/commands/converter.py:116`

Here's the full traceback:
```py
Ignoring exception in command squads promote:
Traceback (most recent call last):
File "C:\Users\saltamimi\.virtualenvs\halobot-rewrite-O1Pbt8pO\lib\site-packages\discord\ext\commands\core.py", line 471, in _actual_conversion
  return await converter().convert(ctx, argument)
File "C:\Users\saltamimi\.virtualenvs\halobot-rewrite-O1Pbt8pO\lib\site-packages\discord\ext\commands\converter.py", line 116, in __init__
  super().__init__()
File "C:\Program Files\Python39\lib\typing.py", line 1083, in _no_init
  raise TypeError('Protocols cannot be instantiated')
TypeError: Protocols cannot be instantiated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\saltamimi\.virtualenvs\halobot-rewrite-O1Pbt8pO\lib\site-packages\discord\ext\commands\bot.py", line 986, in invoke
  await ctx.command.invoke(ctx)
File "C:\Users\saltamimi\.virtualenvs\halobot-rewrite-O1Pbt8pO\lib\site-packages\discord\ext\commands\core.py", line 1361, in invoke
  await ctx.invoked_subcommand.invoke(ctx)
File "C:\Users\saltamimi\.virtualenvs\halobot-rewrite-O1Pbt8pO\lib\site-packages\discord\ext\commands\core.py", line 868, in invoke
  await self.prepare(ctx)
File "C:\Users\saltamimi\.virtualenvs\halobot-rewrite-O1Pbt8pO\lib\site-packages\discord\ext\commands\core.py", line 802, in prepare
  await self._parse_arguments(ctx)
File "C:\Users\saltamimi\.virtualenvs\halobot-rewrite-O1Pbt8pO\lib\site-packages\discord\ext\commands\core.py", line 710, in _parse_arguments
  transformed = await self.transform(ctx, param)
File "C:\Users\saltamimi\.virtualenvs\halobot-rewrite-O1Pbt8pO\lib\site-packages\discord\ext\commands\core.py", line 565, in transform
  return await self.do_conversion(ctx, converter, argument, param)
File "C:\Users\saltamimi\.virtualenvs\halobot-rewrite-O1Pbt8pO\lib\site-packages\discord\ext\commands\core.py", line 518, in do_conversion
  return await self._actual_conversion(ctx, converter, argument, param)
File "C:\Users\saltamimi\.virtualenvs\halobot-rewrite-O1Pbt8pO\lib\site-packages\discord\ext\commands\core.py", line 477, in _actual_conversion
  raise ConversionError(converter, exc) from exc
discord.ext.commands.errors.ConversionError: (<class 'discord.ext.commands.converter.MemberConverter'>, TypeError('Protocols cannot be instantiated'))
```

Now, again, I don't know where the specific spots are where this applies, all I know is this is a bug with Python 3.9.7 and from that, that's why I believe it's certainly easier to just block out 3.9.7 instead of making changes to the underlying codebase. This behavior was patched out on 3.10 and 3.9.6 is unaffected in my uses.

**Comment by GnomedDev** [comment]
We have had no reports of this issue on the support server, and was not reproducible by me back when created. Closing

**Pull request closed without merging**
