### PR TITLE
Add support for creating parties

### PR DESCRIPTION
**Pull request by wasi-master**
## Summary

Adds the same thing as https://www.npmjs.com/package/discord-together and https://pypi.org/project/discord-together/

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

## Additional Info

Any suggestions are appreciated. The documentation needs to be improved for this so this is currently a draft PR

### CODE REVIEW

**Comment by Soheab** [comment]
What is the purpose of this class and method? it's the same as [`Invite`](https://github.com/iDevision/enhanced-discord.py/blob/2.0/discord/invite.py#L210-L498) and [`GuildChannel.create_invite`](https://github.com/iDevision/enhanced-discord.py/blob/2.0/discord/abc.py#L1028-L1104) already has the following kwargs for the activities: `target_type, target_user, target_application_id`. Could maybe use the `PartyType` enum for `Invite.target_application_id` instead?

**Comment by wasi-master** [comment]
Oh, I opened this a long time ago, not exactly sure what the purpose was back then. Is this needed anymore?

**Comment by Soheab** [comment]
> Oh, I opened this a long time ago, not exactly sure what the purpose was back then. Is this needed anymore?

Idk the feature hasn't released yet but if talking about the pr, the PartyType enum like I said might be useful.

**Comment by dolfies** [comment]
This is just an unnecessary abstraction around `Invite`. Also, I don't think we should have an enum for the activity IDs, as there are tons and they are always changing.

**Comment by wasi-master** [comment]
Lol yep, I don’t really remember the purpose behind this PR. I am thinking about closing it for now

**Pull request closed without merging**
