### PR TITLE
Intents.from_list() added

### PR DESCRIPTION
**Pull request by NightSlasher35**
## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by WhoTheOOF — COMMENTED** [review]
I personally would never see myself using this, so I'm just not going to give a positive or negative. It may be good for others though.

**Review by WhoTheOOF — CHANGES_REQUESTED** [review]
Wrong versionadded

**Comment by LenPShard** [comment]
This design seems rather contrived. The constructor already allows similar passing of flags.

This also won't work as expected as you're modifying the list while iterating over it.
Some optimisations could also be made, namely only traversing the list once.

**Comment by IAmTomahawkx** [comment]
I don't see a valid usecase for this that can't be done through the constructor.
Thanks for the PR

**Pull request closed without merging**
