### PR TITLE
Revert #42

### PR DESCRIPTION
**Pull request by Astrea49**
## Summary

Undos #42.

According to https://github.com/nextcord/nextcord/issues/155, it seems like NCPlayz does not wish for his Welcome Screen implementation to be used without his permission. It's unlikely they'll give us permission, nor do we have it right now, so it's safe to assume it should be removed from here.

We'll probably have to make our own implementation of this in the future.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by BobDotCom** [comment]
> "...Been tricky keeping up with all the forks, but yeah, I don't intend to give permission to use my welcome screen implementation to any fork."
*- NCPlayz*

Received this information via DMs on discord.

**Comment by IAmTomahawkx** [comment]
> > "...Been tricky keeping up with all the forks, but yeah, I don't intend to give permission to use my welcome screen implementation to any fork."
> > _- NCPlayz_
> 
> Received this information via DMs on discord.

Hi there, we're already aware of this. Please refrain from micro-managing others. It does not help us, or yourself.

**Comment by BobDotCom** [comment]
I was only trying to help... we had the same [issue](https://github.com/Pycord-Development/pycord/pull/66#issuecomment-915577743)...

**Comment by krittick** [comment]
> > > "...Been tricky keeping up with all the forks, but yeah, I don't intend to give permission to use my welcome screen implementation to any fork."
> > > _- NCPlayz_
> > 
> > 
> > Received this information via DMs on discord.
> 
> Hi there, we're already aware of this. Please refrain from micro-managing others. It does not help us, or yourself.

This type of attitude means I will never use your fork and will now actively tell others in the discord development community to avoid it as its developers appear to be immature. Grow up and try to have some gratitude for someone trying to help.

Thank you @BobDotCom for sharing the copyright issue across multiple forks to ensure its context is fully known. It's appreciated, even if the developers of this particular fork don't seem to think so.

**Comment by maddiethecafebabe** [comment]
I don't think there is a copyright issue here.. 
The welcome screen implementation belongs to [a fork of d.py by the author](https://github.com/NCPlayz/discord.py/blob/v1/guild/welcome-screen/discord/welcome_screen.py) that _[is licensed under MIT](https://github.com/NCPlayz/discord.py/blob/v1/guild/welcome-screen/LICENSE)_ so everyone is free to use it as long as they uphold the original license (which this does).

You can remove it out of courtesy to the author but if they didnt want others to use their code then maybe they shouldn't have licensed their code to the entire world..

**Comment by iDutchy** [comment]
> I don't think there is a copyright issue here.. 
> The welcome screen implementation belongs to [a fork of d.py by the author](https://github.com/NCPlayz/discord.py/blob/v1/guild/welcome-screen/discord/welcome_screen.py) that _[is licensed under MIT](https://github.com/NCPlayz/discord.py/blob/v1/guild/welcome-screen/LICENSE)_ so everyone is free to use it as long as they uphold the original license (which this does).
> 
> You can remove it out of courtesy to the author but if they didnt want others to use their code then maybe they shouldn't have licensed their code to the entire world..

The code was never added to d.py as it was still a PR when d.py closed. Therefore it doesn't fall under d.py's license yet

**Comment by noirscape** [comment]
> The code was never added to d.py as it was still a PR when d.py closed. Therefore it doesn't fall under d.py's license yet

that's not how licenses work.

the forked project is it's own repository, not some dangling piece of code. any contributions made to that repository bear the MIT license, including the specific commits that introduced the welcome screen.

if the same commit had removed the MIT license or had specifically noted that these contributions would go under a different license, you'd have a point. otherwise you do not.

**Comment by maddiethecafebabe** [comment]
> The code was never added to d.py as it was still a PR when d.py closed. Therefore it doesn't fall under d.py's license yet
Hey not trying to be passive aggressive here (i don't really care about this repo or anything, i just see misinformation about Licenses being spreaded) but the two white things in my message are links you can click that directly bring you to a repository of the author where the author pushed the relevant code under d.py's MIT license so the author did in fact license the code under the d.py license - that it wasn't merged with the "original" repo has no relevance on copyright

**Comment by iDutchy** [comment]
> > The code was never added to d.py as it was still a PR when d.py closed. Therefore it doesn't fall under d.py's license yet
> 
> that's not how licenses work.
> 
> the forked project is it's own repository, not some dangling piece of code. any contributions made to that repository bear the MIT license, including the specific commits that introduced the welcome screen.
> 
> if the same commit had removed the MIT license or had specifically noted that these contributions would go under a different license, you'd have a point. otherwise this is nonsense.

> > The code was never added to d.py as it was still a PR when d.py closed. Therefore it doesn't fall under d.py's license yet
> 
> Hey not trying to be passive aggressive here (i don't really care about this repo or anything, i just see misinformation about Licenses being spreaded) but the two white things in my message are links you can click that directly bring you to a repository of the author where the author pushed the relevant code under d.py's MIT license so the author did in fact license the code under the d.py license - that it wasn't merged with the "original" repo has no relevance on copyright


My apologies, it seems my memory has failed me once again. I remembered someone saying it not being part of the license if it's still a PR, but it seems I remembered incorrectly. I personally don't know a lot of in-depth details of licenses, there's so many with so many different rules to them, I usually forget how they exactly work. Thanks for pointing out my incorrect statement, I hope a next time my memory won't fail me on this again :)

**Comment by maddiethecafebabe** [comment]
Np, sorry if I sounded aggressive or something, that's a problem of mine during internet discussions.

I also want to clarify that I'm not saying this PR shouldn't have been merged, as I said it's a thing you can do out of courtesy and I think one doesn't have to be a jerk about things like this if the author asks to please remove said code, it's easy enough to write your own implementation of this.
I just think they (the author) shouldn't act like they have a _right_ to mandate people to remove it from their forks because they don't - they licensed it to everyone under d.py's MIT license and you can't take that back later on because you feel like it. And lying about being in the legal right to get others to do what you want generally makes you seem unlikeable, to me atleast.

**Comment by Astrea49** [comment]
Okay, look, as a contributor of this fork...

I apologize for Tom's rude comment. I can agree that it was too much. Not that it *does not* reflect the attitude of many of the contributors here, or, at least, it doesn't reflect mine - I'm more than willing to get help from other forks! In fact, someone from Nextcord notified me about this problem because we on pretty good terms, and I really cannot say enough how much I appreciate that.

Regardless, I can sense that this will only get more heated. I would lock the PR myself, but I can't. @iDutchy can you lock this? I don't see a benefit of keeping this open - MIT or not, NC has *explictly* said he does not wish for his code to be implemented in any fork, and we're simply respecting that.

**Pull request merged**
